---

env:
    IMAGE_SUFFIX: "c20230110t125740z-f37f36u2204"
    FEDORA_NAME: "fedora-37"
    PRIOR_FEDORA_NAME: "fedora-35" # c20230116t150931z-f37f36u2204
    UBUNTU_NAME: "ubuntu-2204"
    FEDORA_CONTAINER_FQIN: "quay.io/libpod/fedora_podman:c6534102392766464"

validate_task:
    only_if: $CIRRUS_PR != ''
    container: &smallcontainer
        image: $FEDORA_CONTAINER_FQIN  # c20230101t010101z-f36f35u2110
    script: "/bin/true"

success_task:
    name: "Total Success"
    alias: success
    depends_on:
        - validate
    container: *smallcontainer
    clone_script: mkdir -p $CIRRUS_WORKING_DIR
    script: "/bin/true"
