---

env:
    IMAGE_SUFFIX: "c230116-000000-f37-f36-u2204"
    FEDORA_NAME: "fedora-36" ### c230116-000000-f37-f36-u2204
    PRIOR_FEDORA_NAME: "fedora-35"  ### c230116-000000-f37-f36-u2204
    UBUNTU_NAME: "ubuntu-2204" ### c230116-000000-f37-f36-u2204
    FEDORA_CONTAINER_FQIN: "quay.io/libpod/fedora_podman:c6534102392766464"

validate_task:
    only_if: $CIRRUS_PR != ''
    container: &smallcontainer
        image: $FEDORA_CONTAINER_FQIN
    script: "/bin/true"

success_task:
    name: "Total Success"
    alias: success
    depends_on:
        - validate
    container: *smallcontainer
    clone_script: mkdir -p $CIRRUS_WORKING_DIR
    script: "/bin/true"
