---

name: Scan Branches/Tags for secrets leaks

on:
  push:
  workflow_dispatch:

permissions: read-all

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_CONFIG: ${{ github.workspace }}/.github/gitleaks.toml
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
