---

name: Scan PRs for secrets leaks

on:
  pull_request:
  # Block PR modification of workflow & required for access
  # to GITLEAKS_LICENSE secret.
  pull_request_target:

# N/B: Default write-all permission for pull_request_target
permissions: read-all

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main  # Block PR modification of config.
          path: main
          fetch-depth: 0
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_CONFIG: ${{ github.workspace }}/main/.github/gitleaks.toml
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
